from pptx import Presentation

def create_ppt(title, explanation, notes, mcqs):
    prs = Presentation()

    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI StudyVision"

    # Explanation Slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Explanation"
    slide.placeholders[1].text = explanation

    # Notes Slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Notes"
    slide.placeholders[1].text = notes

    # MCQs Slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "MCQs"
    slide.placeholders[1].text = mcqs

    filename = "AI_StudyVision_PPT.pptx"
    prs.save(filename)

    return filename
